# This workflow will install Python dependencies, run tests, and lint with a variety of Python versions.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI build

on:
  pull_request:
    branches:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      max-parallel: 7
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install sbvirtualdisplay
      run: |
        python setup.py install
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are flake8 issues
        flake8 . --count --show-source --statistics --exclude=temp
    - name: Test with pytest
      run: |
        pytest
